# Site settings
title: HAS LAMBDA
description: 하나고등학교 코딩 동아리 LAMBDA
baseurl: / # the subpath of your site, e.g. /blog
url: "http://www.haslambda.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br


# User settings
username: LAMBDA
user_description: 하나고등학교 코딩 동아리
user_title: Hana Academy Seoul Coding Club
email: soarhigh03@gmail.com
twitter_username: none
github_username:  HAS Lambda # https://github.com/haslambda
gplus_username:  none

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
